### ISSUE TITLE
The video has been lost

### ISSUE THREAD

**Issue by bagualing** [vojtechmares/goreleaser-live#1]
The video has been lost.
https://www.youtube.com/watch?v=A99IDxxKmL

**Comment by vojtechmares** [comment]
cc @ondrejsika

**Comment by vojtechmares** [comment]
bump cc @ondrejsika

**Comment by ondrejsika** [comment]
Propper URL is https://www.youtube.com/watch?v=A99IDxxKmL4

**Comment by vojtechmares** [comment]
Closed by https://github.com/vojtechmares/goreleaser-live/commit/b2ccf51b9a24a1ceaf1016ba5ed2a28c2033ef5a
